#!/usr/bin/env python3
"""Regenerate the Bioconductor mapping tables in helpers/.Rprofile.

Both tables come from Bioconductor's own config.yaml:

    bioc_to_r_local    r_ver_for_bioc_ver
    bioc_to_p3m_date   release_dates, shifted by one release: a release's
                       snapshot is the day the next release came out. The
                       newest release has no next one and resolves to latest.

Only the text between the BEGIN/END markers is rewritten.

    python3 scripts/autoupdate/helpers_rprofile.py [--check] [--config FILE]
"""
import argparse
import re
import sys
import urllib.request
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
RPROFILE = ROOT / "helpers" / ".Rprofile"
CONFIG_URL = "https://bioconductor.org/config.yaml"

# Posit Package Manager has no snapshots from before this release.
P3M_FIRST = "3.5"

BEGIN = "  # BEGIN generated by scripts/autoupdate/helpers_rprofile.py\n"
END = "  # END generated\n"


def fetch(url: str) -> str:
    with urllib.request.urlopen(url, timeout=30) as resp:
        return resp.read().decode()


def block(text: str, key: str) -> dict[str, str]:
    """The flat `"a": "b"` lines under a top-level key."""
    out: dict[str, str] = {}
    inside = False
    for line in text.splitlines():
        if re.match(rf"^{key}:", line):
            inside = True
            continue
        if inside:
            m = re.match(r'^\s+"([^"]+)":\s*"([^"]+)"', line)
            if m:
                out[m.group(1)] = m.group(2)
            elif line.strip() and not line.lstrip().startswith("#"):
                break
    if not out:
        raise SystemExit(f"config.yaml has no {key} block")
    return out


def version_key(v: str) -> tuple[int, ...]:
    return tuple(int(part) for part in v.split("."))


def snapshot_dates(release_dates: dict[str, str]) -> dict[str, str]:
    """Release N maps to the date release N+1 was published."""
    versions = sorted(release_dates, key=version_key)
    dates = {v: datetime.strptime(release_dates[v], "%m/%d/%Y").date() for v in versions}
    out: dict[str, str] = {}
    for prev, nxt in zip(versions, versions[1:]):
        if version_key(prev) < version_key(P3M_FIRST):
            continue
        if dates[nxt] <= dates[prev]:
            raise SystemExit(f"release dates go backwards at {prev} -> {nxt}")
        out[prev] = dates[nxt].isoformat()
    return out


def table(name: str, rows: dict[str, str]) -> str:
    keys = sorted(rows, key=version_key)
    body = ",\n".join(f'    "{k}" = "{rows[k]}"' for k in keys)
    return f"  {name} <- c(\n{body}\n  )\n"


def existing(text: str, name: str) -> dict[str, str]:
    m = re.search(rf"{name} <- c\((.*?)\n  \)", text, re.S)
    return dict(re.findall(r'"([^"]+)" = "([^"]+)"', m.group(1))) if m else {}


class Refused(Exception):
    """The regenerated tables cannot be trusted."""


def regenerate(config: str) -> tuple[str, str, str]:
    """Return the file's current text, its regenerated text, and what was added."""
    r_local = block(config, "r_ver_for_bioc_ver")
    p3m = snapshot_dates(block(config, "release_dates"))

    text = RPROFILE.read_text()
    start, stop = text.find(BEGIN), text.find(END)
    if start < 0 or stop < start:
        raise Refused("no BEGIN/END generated markers")

    added = []
    # An upstream table that lost rows is a bad fetch, not a release.
    for name, new in (("bioc_to_r_local", r_local), ("bioc_to_p3m_date", p3m)):
        old = existing(text, name)
        lost = set(old) - set(new)
        if lost:
            raise Refused(f"{name} would lose {', '.join(sorted(lost, key=version_key))}")
        gained = sorted(set(new) - set(old), key=version_key)
        if gained:
            added.append(f"{name} +{', '.join(gained)}")

    generated = BEGIN + table("bioc_to_p3m_date", p3m) + "\n" + table("bioc_to_r_local", r_local) + END
    updated = text[:start] + generated + text[stop + len(END):]
    return text, updated, "; ".join(added) or "values changed"


def main() -> int:
    """Print one [UPDATED], [SKIP] or [FAIL] line, the form the workflow's
    summary and failure report read."""
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="exit 1 when the file is stale")
    ap.add_argument("--config", type=Path, help="read this config.yaml instead of fetching it")
    args = ap.parse_args()

    label = "helpers/.Rprofile"
    try:
        config = args.config.read_text() if args.config else fetch(CONFIG_URL)
        text, updated, what = regenerate(config)
    except (Refused, OSError, SystemExit) as err:
        print(f"[FAIL] {label}: {err}", file=sys.stderr)
        return 1

    if updated == text:
        print(f"[SKIP] {label}: up to date")
        return 0
    if args.check:
        print(f"[FAIL] {label}: stale, run scripts/autoupdate/helpers_rprofile.py", file=sys.stderr)
        return 1
    RPROFILE.write_text(updated)
    print(f"[UPDATED] {label}: {what}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
